apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: soccerfootballstuff-players-svc
build:
  artifacts:
    - image: jzenon13/soccerfootballstuff-players
      context: .
      sync:
        manual:
          - src: src/**/*.js
            dest: .
      docker:
        dockerfile: Dockerfile
portForward:
  - resourceType: service
    resourceName: soccerfootballstuff-players-svc
    port: 3002
manifests:
  rawYaml:
    - ./infra/k8s/*
