apiVersion: apps/v1
kind: Deployment
metadata:
  name: soccerfootballstuff-teams-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soccerfootballstuff-teams
  template:
    metadata:
      labels:
        app: soccerfootballstuff-teams
    spec:
      containers:
        - name: teams
          image: jzenon13/soccerfootballstuff-teams
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "300Mi"
              cpu: "500m"
            limits:
              memory: "600Mi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: soccerfootballstuff-teams-svc
spec:
  selector:
    app: soccerfootballstuff-teams
  ports:
    - name: soccerfootballstuff-teams
      protocol: TCP
      port: 3003
      targetPort: 3000
