apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: soccerfootballstuff-leagues-svc
build:
  artifacts:
    - image: jzenon13/soccerfootballstuff-leagues
      context: .
      sync:
        manual:
          - src: src/**/*.js
            dest: .
      docker:
        dockerfile: Dockerfile
portForward:
  - resourceType: service
    resourceName: soccerfootballstuff-leagues-svc
    port: 3001
manifests:
  rawYaml:
    - ./infra/k8s/*
