apiVersion: apps/v1
kind: Deployment
metadata:
  name: soccerfootballstuff-leagues-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soccerfootballstuff-leagues
  template:
    metadata:
      labels:
        app: soccerfootballstuff-leagues
    spec:
      containers:
        - name: soccerfootballstuff-leagues
          image: jzenon13/soccerfootballstuff-leagues
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "300Mi"
              cpu: "500m"
            limits:
              memory: "600Mi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: soccerfootballstuff-leagues-svc
spec:
  selector:
    app: soccerfootballstuff-leagues
  ports:
    - name: soccerfootballstuff-leagues
      protocol: TCP
      port: 3001
      targetPort: 3000
