apiVersion: apps/v1
kind: Deployment
metadata:
  name: soccerfootballstuff-players-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soccerfootballstuff-players
  template:
    metadata:
      labels:
        app: soccerfootballstuff-players
    spec:
      containers:
        - name: soccerfootballstuff-players
          image: jzenon13/soccerfootballstuff-players
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "300Mi"
              cpu: "500m"
            limits:
              memory: "600Mi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: soccerfootballstuff-players-svc
spec:
  selector:
    app: soccerfootballstuff-players
  ports:
    - name: soccerfootballstuff-players
      protocol: TCP
      port: 3002
      targetPort: 3000
